### ISSUE TITLE
`make tests` errors out with version 2.7

### ISSUE THREAD

**Issue by avdv** [madler/pigz#109]
The reason is `pigzn` cannot be build anymore:

```console
$ make tests
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual   -c -o pigz.o pigz.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual   -c -o yarn.o yarn.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual   -c -o try.o try.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/deflate.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/blocksplitter.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/tree.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/lz77.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/cache.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/hash.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/util.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/squeeze.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/katajainen.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/symbols.c
gcc  -o pigz pigz.o yarn.o try.o deflate.o blocksplitter.o tree.o lz77.o cache.o hash.o util.o squeeze.o katajainen.o symbols.o -lm -lpthread -lz
ln -f pigz unpigz
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -DNOZOPFLI -c -o pigzj.o pigz.c
gcc  -o pigzj pigzj.o yarn.o try.o -lm -lpthread -lz
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -DPIGZ_DEBUG -g -c -o pigzt.o pigz.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -DPIGZ_DEBUG -g -c -o yarnt.o yarn.c
gcc  -o pigzt pigzt.o yarnt.o try.o deflate.o blocksplitter.o tree.o lz77.o cache.o hash.o util.o squeeze.o katajainen.o symbols.o -lm -lpthread -lz
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -DPIGZ_DEBUG -DNOTHREAD -g -c -o pigzn.o pigz.c
pigz.c: In function ‘infchk’:
pigz.c:3598:20: warning: implicit declaration of function ‘COMB’ [-Wimplicit-function-declaration]
 3598 |             ktot = COMB(ktot, check, g.out_tot);
      |                    ^~~~
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -DPIGZ_DEBUG -DNOTHREAD -g -c -o tryn.o try.c
gcc  -o pigzn pigzn.o tryn.o deflate.o blocksplitter.o tree.o lz77.o cache.o hash.o util.o squeeze.o katajainen.o symbols.o -lm -lpthread -lz
/nix/store/lz1bwpdvlywij5ir0fmncgqa83dlpwhn-binutils-2.39/bin/ld: pigzn.o: in function `infchk':
/home/claudio/source/pigz-2.7/pigz.c:3598: undefined reference to `COMB'
collect2: error: ld returned 1 exit status
make: *** [Makefile:72: pigzn] Error 1
```

This regression was introduced by commit https://github.com/madler/pigz/commit/364f970652910452ccd5c1037dfa9e80ef5989ac

**Comment by avdv** [comment]
Oh, thank you! I didn't realize the main branch is not the main line of development...
